[project]
name = "osi-troubleshooter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.124.2",
    "paramiko>=4.0.0",
    "pysnmp>=7.1.22",
    "uvicorn>=0.38.0",
]
